version: 3

tasks:
  default:
    cmds:
      - task: test

  build:
    cmds:
      - odin build sandbox -out=bin/sandbox
    aliases:
      - b
    silent: true
    sources:
      - ./sandbox/**/*.odin
    generates:
      - bin/sandbox

  test:
    cmds:
      - odin test sandbox
    aliases:
      - t
    method: none
    silent: true
    sources:
      - ./sandbox/**/*.odin

interval: 250ms
