version: 3

tasks:
  default:
    cmds:
      - task: test

  run:
    deps:
      - build
    cmds:
      - bin/sandbox
    silent: true
    method: none

  build:
    cmds:
      - odin build sandbox -out=bin/sandbox
    aliases:
      - b
    silent: true
    sources:
      - ./sandbox/**/*.odin
    generates:
      - bin/sandbox

  build_debug:
    cmds:
      - odin build sandbox -out=bin/sandbox-debug -o:none -debug
    aliases:
      - bd
    silent: true
    sources:
      - ./sandbox/**/*.odin
    generates:
      - bin/sandbox-debug

  build_sgrep:
    cmds:
      - odin build sgrep -out:bin/sgrep -o:speed -collection:dependencies=dependencies
    aliases:
      - bs
    silent: true
    sources:
      - ./sgrep/**/*.odin
    generates:
      - bin/sgrep

  sgrep:
    deps:
      - build_sgrep
    cmds:
      - bin/sgrep
    silent: true
    method: none

  debug:
    deps:
      - build_debug
    cmds:
      - gdb bin/sandbox-debug
    aliases:
      - d
    silent: true
    method: none

  test:
    cmds:
      - odin test sandbox
    aliases:
      - t
    method: none
    silent: true
    sources:
      - ./sandbox/**/*.odin
  
  test_uuid:
    cmds:
      - odin test uuid
    aliases:
      - tu
    method: none
    silent: true
    sources:
      - ./uuid/**/*.odin

  build_testcase:
    cmds:
      - odin build testcase -out:bin/testcase -o:none -debug
    silent: true
    sources:
      - ./testcase/**/*.odin
    generates:
      - bin/testcase

  testcase:
    deps:
      - build_testcase
    cmds:
      - gdb bin/testcase
    silent: true
    method: none

  types_and_data:
    deps:
      - build_types_and_data
    silent: true
    cmds:
      - bin/types-and-data {{.CLI_ARGS}}
    method: none

  build_types_and_data:
    cmds:
      - odin build types-and-data -out:bin/types-and-data -o:none -debug
    silent: true
    sources:
      - ./types-and-data/**/*.odin
    generates:
      - bin/types-and-data

  bits_and_bobs:
    deps:
      - build_bits_and_bobs
    silent: true
    cmds:
      - bin/bits-and-bobs {{.CLI_ARGS}}
    method: none

  build_bits_and_bobs:
    cmds:
      - odin build bits-and-bobs -out:bin/bits-and-bobs -o:none -debug
    silent: true
    sources:
      - ./bits-and-bobs/**/*.odin
    generates:
      - bin/bits-and-bobs

  build_lz4_frames:
    cmds:
      - odin build lz4-frames -out:bin/lz4-frames -o:speed
    silent: true
    sources:
      - ./lz4-frames/**/*.odin
    generates:
      - bin/lz4-frames

interval: 250ms
