version: 3

tasks:
  default:
    cmds:
      - task: test

  run:
    deps:
      - build
    cmds:
      - bin/sandbox
    silent: true
    method: none

  build:
    cmds:
      - odin build sandbox -out=bin/sandbox
    aliases:
      - b
    silent: true
    sources:
      - ./sandbox/**/*.odin
    generates:
      - bin/sandbox

  build_debug:
    cmds:
      - odin build sandbox -out=bin/sandbox-debug -o:none -debug
    aliases:
      - bd
    silent: true
    sources:
      - ./sandbox/**/*.odin
    generates:
      - bin/sandbox-debug

  build_sgrep:
    cmds:
      - odin build sgrep -out:bin/sgrep -o:speed
    aliases:
      - bs
    silent: true
    sources:
      - ./sgrep/**/*.odin
    generates:
      - bin/sgrep

  sgrep:
    deps:
      - build_sgrep
    cmds:
      - bin/sgrep
    silent: true
    method: none

  debug:
    deps:
      - build_debug
    cmds:
      - gdb bin/sandbox-debug
    aliases:
      - d
    silent: true
    method: none

  test:
    cmds:
      - odin test sandbox
    aliases:
      - t
    method: none
    silent: true
    sources:
      - ./sandbox/**/*.odin

  build_testcase:
    cmds:
      - odin build testcase -out:bin/testcase -o:none -debug
    silent: true
    sources:
      - ./testcase/**/*.odin
    generates:
      - bin/testcase

  testcase:
    deps:
      - build_testcase
    cmds:
      - gdb bin/testcase
    silent: true
    method: none

interval: 250ms
